global using FubuCsprojFile.MSBuild;
global using FubuCsprojFile;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.IO;
global using System.Linq;
global using System;
global using Xunit;
global using System.Threading.Tasks;
