<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest.TestAdapter">
      <Version>3.1.1</Version>
    </PackageReference>
    <PackageReference Include="MSTest.TestFramework">
      <Version>3.1.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="*" Pack="True" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\sunamo.notmine.unknownoriginal\Metaproject.PackageIndex.Functions.ParseCsprojFile\Metaproject.PackageIndex.Functions.ParseCsprojFile.csproj" />
    <ProjectReference Include="..\sunamo.notmine.unknownoriginal\Metaproject.PackageIndex.Structures.PackageProject\Metaproject.PackageIndex.Structures.PackageProject.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="_.txt" />
  </ItemGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);ASYNC</DefineConstants>
    <NoWarn>CA1822;CS1573;CS1572;CS1570;CA1866;CA1865;CA1867;CS1998;CA1847;IDE0066</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants);ASYNC</DefineConstants>
    <NoWarn>CA1822;CS1573;CS1572;CS1570;CA1866;CA1865;CA1867;CS1998;CA1847;IDE0066</NoWarn>
  </PropertyGroup>
</Project>